plugins { id 'com.android.application' }

android {
    namespace 'com.example.rcscontainerbind'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.rcscontainerbind'
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName '1.2'
        testInstrumentationRunner 'android.test.InstrumentationTestRunner'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    testOptions { unitTests.returnDefaultValues = true }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}
